### ISSUE TITLE
npm install error because of certificate

### ISSUE THREAD

**Issue by SejoongDeJang** [microsoft/vscode-ripgrep#21]
``` terminal
$ npm install --save vscode-ripgrep

> vscode-ripgrep@1.12.0 postinstall /home/sejoong/workspace/node_modules/vscode-ripgrep
> node ./lib/postinstall.js

Finding release for v13.0.0-1
GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v13.0.0-1
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
```

Even I set http.proxy https.proxy and cafile on `npm config` and set environment variables(HTTP_PROXY, HTTPS_PROXY,http_proxy, https_proxy), the package is failed install.

Also I tried to install with the `export NODE_TLS_REJECT_UNAUTHORIZED=0`, but it failed too.

Can you tell me how to resolve it?

**Comment by roblourens** [comment]
Sorry, I am not sure what that means. I think this is an issue with npm, not this package.
